env:
  browser: true
  es2021: true
  jest: true  

extends:
  - airbnb-base

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  no-console: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  no-prototype-builtins: 0
  import/no-relative-packages: "off"  # Disable this rule to allow relative imports

settings:
  import/resolver:
    extensions:
      - .js
